// ===================== ФАЙЛ БАЗЫ ДАННЫХ (data.js) =====================

const CAR_DATABASE = {
    economy: [
        { name: "Ока (ВАЗ-1111)", power: 33, basePrice: 40000, type: "economy", img: "assets/cars/economy/oka.jpg" },
        { name: "ЗАЗ-968М «Запорожец»", power: 40, basePrice: 35000, type: "economy", img: "assets/cars/economy/zaz.jpg" },
        { name: "Москвич-412", power: 75, basePrice: 50000, type: "economy", img: "assets/cars/economy/moskvich.jpg" },
        { name: "ИЖ-2126 «Ода»", power: 73, basePrice: 55000, type: "economy", img: "assets/cars/economy/izh.jpg" },
        { name: "ВАЗ-2101 «Копейка»", power: 64, basePrice: 65000, type: "economy", img: "assets/cars/economy/vaz-2101.jpg" },
        { name: "ВАЗ-2106 «Шестерка»", power: 75, basePrice: 75000, type: "economy", img: "assets/cars/economy/vaz-2106.jpg" },
        { name: "ВАЗ-2107 «Семёрка»", power: 74, basePrice: 95000, type: "economy", img: "assets/cars/economy/vaz-2107.jpg" },
        { name: "ВАЗ-2108 «Зубило»", power: 70, basePrice: 110000, type: "economy", img: "assets/cars/economy/vaz-2108.jpg" },
        { name: "ВАЗ-2109 «Девятка»", power: 72, basePrice: 125000, type: "economy", img: "assets/cars/economy/vaz-2109.jpg" },
        { name: "ВАЗ-2110 «Десятка»", power: 89, basePrice: 135000, type: "economy", img: "assets/cars/economy/vaz-2110.jpg" },
        { name: "ВАЗ-2114 «Четырка»", power: 81, basePrice: 140000, type: "economy", img: "assets/cars/economy/vaz-2114.jpg" },
        { name: "ГАЗ-3110 «Волга»", power: 130, basePrice: 120000, type: "economy", img: "assets/cars/economy/volga.jpg" },
        { name: "Lada Kalina I", power: 81, basePrice: 220000, type: "economy", img: "assets/cars/economy/kalina.jpg" },
        { name: "Lada Priora", power: 98, basePrice: 280000, type: "economy", img: "assets/cars/economy/priora.jpg" },
        { name: "Daewoo Matiz", power: 51, basePrice: 120000, type: "economy", img: "assets/cars/economy/matiz.jpg" },
        { name: "Daewoo Nexia", power: 80, basePrice: 150000, type: "economy", img: "assets/cars/economy/nexia.jpg" },
        { name: "Chevrolet Lanos", power: 86, basePrice: 170000, type: "economy", img: "assets/cars/economy/lanos.jpg" },
        { name: "Renault Logan I", power: 75, basePrice: 350000, type: "economy", img: "assets/cars/economy/logan.jpg" },
        { name: "Nissan Almera Classic", power: 107, basePrice: 400000, type: "economy", img: "assets/cars/economy/almera.jpg" },
        { name: "Ford Focus I", power: 100, basePrice: 300000, type: "economy", img: "assets/cars/economy/focus1.jpg" },
        { name: "Hyundai Solaris I", power: 123, basePrice: 620000, type: "economy", img: "assets/cars/economy/solaris.jpg" },
        { name: "Kia Rio 3", power: 123, basePrice: 650000, type: "economy", img: "assets/cars/economy/rio.jpg" },
        { name: "BMW E34 520i (Гнилая)", power: 150, basePrice: 250000, type: "economy", img: "assets/cars/economy/e34.jpg" },
        { name: "Mercedes W210 (Лупатый)", power: 136, basePrice: 300000, type: "economy", img: "assets/cars/economy/w210.jpg" },
        { name: "BMW E38 740i (Требует вложений)", power: 286, basePrice: 450000, type: "economy", img: "assets/cars/economy/e38.jpg" },
        { name: "Audi A6 C5 (Проблемы с АКПП)", power: 165, basePrice: 350000, type: "economy", img: "assets/cars/economy/a6c5.jpg" },
        { name: "Range Rover P38 (Пневма упала)", power: 218, basePrice: 400000, type: "economy", img: "assets/cars/economy/p38.jpg" },
        { name: "Porsche Cayenne 955 (Задиры)", power: 340, basePrice: 500000, type: "economy", img: "assets/cars/economy/cayenne_old.jpg" },
        { name: "Mercedes W140 S500 (Кабан)", power: 320, basePrice: 600000, type: "economy", img: "assets/cars/economy/w140.jpg" }
    ],
    scooter: [
        { name: "Honda Dio AF34", power: 7, basePrice: 45000, type: "scooter", img: "assets/moto/dio.jpg" },
        { name: "Yamaha Jog ZR", power: 8, basePrice: 55000, type: "scooter", img: "assets/moto/jog.jpg" },
        { name: "Suzuki Lets 2", power: 6, basePrice: 35000, type: "scooter", img: "assets/moto/lets.jpg" },
        { name: "Vespa LX 125", power: 10, basePrice: 120000, type: "scooter", img: "assets/moto/vespa.jpg" }
    ],
    moto: [
        { name: "Bajaj Pulsar NS200", power: 25, basePrice: 240000, type: "moto", img: "assets/moto/pulsar.jpg" },
        { name: "Kawasaki Ninja 300", power: 39, basePrice: 450000, type: "moto", img: "assets/moto/ninja.jpg" },
        { name: "Honda CB400 Super Four", power: 53, basePrice: 350000, type: "moto", img: "assets/moto/cb400.jpg" },
        { name: "Yamaha MT-07", power: 74, basePrice: 890000, type: "moto", img: "assets/moto/mt07.jpg" },
        { name: "KTM 390 Duke", power: 44, basePrice: 550000, type: "moto", img: "assets/moto/duke.jpg" },
        { name: "Harley-Davidson Iron 883", power: 51, basePrice: 1200000, type: "moto", img: "assets/moto/iron883.jpg" },
        { name: "Triumph Bonneville T100", power: 55, basePrice: 1300000, type: "moto", img: "assets/moto/bonneville.jpg" },
        { name: "Kawasaki Z900", power: 125, basePrice: 1100000, type: "moto", img: "assets/moto/z900.jpg" },
        { name: "BMW R1250GS", power: 136, basePrice: 2500000, type: "moto", img: "assets/moto/gs1250.jpg" },
        { name: "Suzuki Hayabusa", power: 197, basePrice: 1800000, type: "moto", img: "assets/moto/hayabusa.jpg" },
        { name: "Yamaha YZF-R1", power: 200, basePrice: 2200000, type: "moto", img: "assets/moto/r1.jpg" },
        { name: "Ducati Panigale V4", power: 214, basePrice: 3200000, type: "moto", img: "assets/moto/ducati.jpg" }
    ],
    atv: [
        { name: "CFMOTO CFORCE 500", power: 35, basePrice: 620000, type: "atv", img: "assets/moto/cforce.jpg" },
        { name: "Stels Guepard 850", power: 71, basePrice: 950000, type: "atv", img: "assets/moto/guepard.jpg" },
        { name: "Suzuki KingQuad 750", power: 50, basePrice: 1200000, type: "atv", img: "assets/moto/kingquad.jpg" },
        { name: "Polaris Sportsman 850", power: 78, basePrice: 1600000, type: "atv", img: "assets/moto/sportsman.jpg" },
        { name: "Yamaha Grizzly 700", power: 49, basePrice: 1400000, type: "atv", img: "assets/moto/grizzly.jpg" },
        { name: "BRP Can-Am Maverick", power: 195, basePrice: 3500000, type: "atv", img: "assets/moto/maverick.jpg" }
    ],
    comfort: [
        { name: "VW Polo Sedan", power: 110, basePrice: 850000, type: "comfort", img: "assets/cars/comfort/polo.jpg" },
        { name: "Ford Focus III", power: 125, basePrice: 950000, type: "comfort", img: "assets/cars/comfort/focus.jpg" },
        { name: "Chevrolet Cruze", power: 109, basePrice: 750000, type: "comfort", img: "assets/cars/comfort/cruze.jpg" },
        { name: "Hyundai Elantra", power: 128, basePrice: 1100000, type: "comfort", img: "assets/cars/comfort/elantra.jpg" },
        { name: "Kia Cerato", power: 130, basePrice: 1150000, type: "comfort", img: "assets/cars/comfort/cerato.jpg" },
        { name: "Skoda Octavia A7 1.8", power: 180, basePrice: 1450000, type: "comfort", img: "assets/cars/comfort/octavia.jpg" },
        { name: "VW Jetta", power: 150, basePrice: 1300000, type: "comfort", img: "assets/cars/comfort/jetta.jpg" },
        { name: "Opel Astra J", power: 140, basePrice: 850000, type: "comfort", img: "assets/cars/comfort/astra.jpg" },
        { name: "Peugeot 408", power: 120, basePrice: 900000, type: "comfort", img: "assets/cars/comfort/peugeot408.jpg" },
        { name: "Toyota Corolla E150", power: 124, basePrice: 1050000, type: "comfort", img: "assets/cars/comfort/corolla.jpg" },
        { name: "Mazda 3 (BM)", power: 120, basePrice: 1250000, type: "comfort", img: "assets/cars/comfort/mazda3.jpg" },
        { name: "Ford Mondeo V", power: 149, basePrice: 1600000, type: "comfort", img: "assets/cars/comfort/mondeo.jpg" },
        { name: "Hyundai Sonata", power: 150, basePrice: 1900000, type: "comfort", img: "assets/cars/comfort/sonata.jpg" },
        { name: "Kia Optima", power: 150, basePrice: 1850000, type: "comfort", img: "assets/cars/comfort/optima.jpg" },
        { name: "Toyota Camry XV50", power: 181, basePrice: 1800000, type: "comfort", img: "assets/cars/comfort/camry.jpg" },
        { name: "Kia K5", power: 194, basePrice: 2400000, type: "comfort", img: "assets/cars/comfort/k5.jpg" },
        { name: "VW Golf VI GTI", power: 260, basePrice: 1450000, type: "comfort", img: "assets/cars/comfort/golf6.jpg" },
        { name: "Renault Duster", power: 143, basePrice: 1100000, type: "comfort", img: "assets/cars/comfort/duster.jpg" },
        { name: "Hyundai Creta", power: 123, basePrice: 1500000, type: "comfort", img: "assets/cars/comfort/creta.jpg" },
        { name: "Nissan Qashqai", power: 144, basePrice: 1600000, type: "comfort", img: "assets/cars/comfort/qashqai.jpg" },
        { name: "Skoda Karoq", power: 150, basePrice: 2100000, type: "comfort", img: "assets/cars/comfort/karoq.jpg" },
        { name: "Toyota RAV4", power: 149, basePrice: 2500000, type: "comfort", img: "assets/cars/comfort/rav4.jpg" },
        { name: "Mazda CX-5", power: 150, basePrice: 2300000, type: "comfort", img: "assets/cars/comfort/cx5.jpg" },
        { name: "Geely Coolray", power: 150, basePrice: 2100000, type: "comfort", img: "assets/cars/comfort/coolray.jpg" },
        { name: "Haval Jolion", power: 150, basePrice: 2000000, type: "comfort", img: "assets/cars/comfort/jolion.jpg" }
    ],
    premium: [
        { name: "BMW 5 Series (G30)", power: 190, basePrice: 3500000, type: "premium", img: "assets/cars/premium/g30.jpg" },
        { name: "Mercedes E-Class (W213)", power: 197, basePrice: 3800000, type: "premium", img: "assets/cars/premium/w213.jpg" },
        { name: "Audi A6 (C8)", power: 245, basePrice: 4000000, type: "premium", img: "assets/cars/premium/a6.jpg" },
        { name: "BMW X7", power: 184, basePrice: 3800000, type: "premium", img: "assets/cars/premium/bmwx7.jpg" },
        { name: "Mercedes C63s AMG", power: 197, basePrice: 4200000, type: "premium", img: "assets/cars/premium/mercedes_c_с63_w205_sedan.jpeg" },
        { name: "BMW M340i", power: 249, basePrice: 4800000, type: "premium", img: "assets/cars/premium/bmw_m_340i.jpeg" },
        { name: "Lexus RX 350", power: 300, basePrice: 5500000, type: "premium", img: "assets/cars/premium/rx350.jpg" },
        { name: "Porsche Macan S", power: 354, basePrice: 6500000, type: "premium", img: "assets/cars/premium/macan.jpg" },
        { name: "Audi Q7", power: 249, basePrice: 7000000, type: "premium", img: "assets/cars/premium/q7.jpg" },
        { name: "BMW X5 (G05)", power: 340, basePrice: 8500000, type: "premium", img: "assets/cars/premium/x5.jpg" },
        { name: "BMW X6 (G06)", power: 340, basePrice: 9000000, type: "premium", img: "assets/cars/premium/x6.jpg" },
        { name: "Mercedes GLE 400d", power: 330, basePrice: 9500000, type: "premium", img: "assets/cars/premium/gle.jpg" },
        { name: "Porsche Cayenne (PO536)", power: 340, basePrice: 10500000, type: "premium", img: "assets/cars/premium/cayenne_new.jpg" },
        { name: "Audi Q8", power: 340, basePrice: 9800000, type: "premium", img: "assets/cars/premium/q8.jpg" },
        { name: "Lexus LX 600", power: 415, basePrice: 14000000, type: "premium", img: "assets/cars/premium/lx600.jpg" },
        { name: "Toyota Land Cruiser 300", power: 415, basePrice: 12000000, type: "premium", img: "assets/cars/premium/lc300.jpg" },
        { name: "Range Rover Sport", power: 400, basePrice: 13500000, type: "premium", img: "assets/cars/premium/rr_sport.jpg" },
        { name: "Volvo XC90", power: 235, basePrice: 6800000, type: "premium", img: "assets/cars/premium/xc90.jpg" },
        { name: "Genesis GV80", power: 249, basePrice: 7500000, type: "premium", img: "assets/cars/premium/gv80.jpg" },
        { name: "Cadillac Escalade", power: 416, basePrice: 11000000, type: "premium", img: "assets/cars/premium/escalade.jpg" },
        { name: "Infiniti QX80", power: 405, basePrice: 8500000, type: "premium", img: "assets/cars/premium/qx80.jpg" },
        { name: "Maserati Levante", power: 350, basePrice: 9000000, type: "premium", img: "assets/cars/premium/levante.jpg" },
        { name: "Mercedes S-Class (W223)", power: 367, basePrice: 16000000, type: "premium", img: "assets/cars/premium/w223.jpg" },
        { name: "BMW 7 Series (G70)", power: 381, basePrice: 15500000, type: "premium", img: "assets/cars/premium/g70.jpg" },
        { name: "Mercedes G63 AMG", power: 585, basePrice: 14500000, type: "premium", img: "assets/cars/premium/mercedes_g63amg.jpg" }
    ],
    hyper: [
        { name: "Nissan GT-R R35", power: 570, basePrice: 12000000, type: "hyper", img: "assets/cars/hyper/gtr.jpg" },
        { name: "Porsche 911 GT3 RS", power: 525, basePrice: 29000000, type: "hyper", img: "assets/cars/hyper/911.jpg" },
        { name: "Lamborghini Huracan", power: 640, basePrice: 35000000, type: "hyper", img: "assets/cars/hyper/huracan.jpg" },
        { name: "Ferrari SF90 Stradale", power: 1000, basePrice: 75000000, type: "hyper", img: "assets/cars/hyper/sf90.jpg" },
        { name: "McLaren 720S", power: 720, basePrice: 32000000, type: "hyper", img: "assets/cars/hyper/mclaren.jpg" },
        { name: "Lamborghini Aventador SVJ", power: 770, basePrice: 65000000, type: "hyper", img: "assets/cars/hyper/aventador.jpg" },
        { name: "Porsche 918 Spyder", power: 887, basePrice: 120000000, type: "hyper", img: "assets/cars/hyper/918.jpg" },
        { name: "McLaren P1", power: 916, basePrice: 140000000, type: "hyper", img: "assets/cars/hyper/p1.jpg" },
        { name: "LaFerrari", power: 963, basePrice: 250000000, type: "hyper", img: "assets/cars/hyper/laferrari.jpg" },
        { name: "Bugatti Chiron", power: 1500, basePrice: 350000000, type: "hyper", img: "assets/cars/hyper/chiron.jpg" },
        { name: "Koenigsegg Jesko", power: 1600, basePrice: 400000000, type: "hyper", img: "assets/cars/hyper/jesko.jpg" },
        { name: "Pagani Huayra", power: 730, basePrice: 280000000, type: "hyper", img: "assets/cars/hyper/huayra.jpg" },
        { name: "Aston Martin Valkyrie", power: 1160, basePrice: 380000000, type: "hyper", img: "assets/cars/hyper/valkyrie.jpg" }
    ],
    truck: [
        { name: "ЗИЛ-130 (С колхоза)", power: 150, basePrice: 250000, type: "truck", img: "assets/cars/truck/zil.jpg" },
        { name: "Урал NEXT", power: 312, basePrice: 4500000, type: "truck", img: "assets/cars/truck/ural.jpg" },
        { name: "ГАЗель NEXT", power: 149, basePrice: 1800000, type: "truck", img: "assets/cars/truck/gazel.jpg" },
        { name: "КАМАЗ-54901 Continent", power: 460, basePrice: 7200000, type: "truck", img: "assets/cars/truck/kamaz.jpg" },
        { name: "DAF XF 105", power: 460, basePrice: 4500000, type: "truck", img: "assets/cars/truck/daf.jpg" },
        { name: "MAN TGX", power: 480, basePrice: 9500000, type: "truck", img: "assets/cars/truck/man.jpg" },
        { name: "Mercedes-Benz Actros", power: 510, basePrice: 12000000, type: "truck", img: "assets/cars/truck/actros.jpg" },
        { name: "Iveco Stralis", power: 460, basePrice: 3800000, type: "truck", img: "assets/cars/truck/iveco.jpg" },
        { name: "Renault T-High", power: 520, basePrice: 8500000, type: "truck", img: "assets/cars/truck/renault_t.jpg" },
        { name: "Freightliner Cascadia", power: 505, basePrice: 6500000, type: "truck", img: "assets/cars/truck/freightliner.jpg" },
        { name: "Peterbilt 389", power: 550, basePrice: 14000000, type: "truck", img: "assets/cars/truck/peterbilt.jpg" },
        { name: "Kenworth W900", power: 600, basePrice: 15500000, type: "truck", img: "assets/cars/truck/kenworth.jpg" },
        { name: "Volvo FH16", power: 750, basePrice: 15500000, type: "truck", img: "assets/cars/truck/volvo.jpg" }
    ],
    yacht: [
        { name: "Гидроцикл Yamaha FX", power: 250, basePrice: 1800000, type: "yacht", img: "assets/water/yamaha.jpg" },
        { name: "Катер Bayliner VR5", power: 200, basePrice: 4500000, type: "yacht", img: "assets/water/bayliner.jpg" },
        { name: "Azimut Atlantis 45", power: 880, basePrice: 75000000, type: "yacht", img: "assets/water/azimut.jpg" },
        { name: "Sunseeker 95 Yacht", power: 3900, basePrice: 450000000, type: "yacht", img: "assets/water/sunseeker.jpg" }
    ]
};

const HOUSING_LIST = [
    { id: 'trailer', name: 'Бытовка на стройплощадке', rent: 800, buyPrice: 0, slots: 0, moodBonus: -5, minLevel: 1, img: 'assets/houses/trailer.jpg' },
    { id: 'room', name: 'Комната в общежитии', rent: 2500, buyPrice: 1800000, slots: 1, moodBonus: 5, minLevel: 2, img: 'assets/houses/room.jpg' },
    { id: 'khrusch', name: 'Убитая "Хрущевка"', rent: 15000, buyPrice: 4500000, slots: 1, moodBonus: 10, minLevel: 6, img: 'assets/houses/khrusch.jpg' },
    { id: 'garage', name: 'Кирпичный гараж с ямой', rent: 18000, buyPrice: 3000000, slots: 3, moodBonus: 12, minLevel: 10, img: 'assets/houses/garage.jpg' },
    { id: 'dvushka', name: 'Двушка в спальном районе', rent: 25000, buyPrice: 8500000, slots: 2, moodBonus: 15, minLevel: 15, img: 'assets/houses/dvushka.jpg' },
    { id: 'euro_treshka', name: 'Евро-трешка (Новостройка)', rent: 45000, buyPrice: 15000000, slots: 3, moodBonus: 25, minLevel: 22, img: 'assets/houses/treshka.jpg' },
    { id: 'cottage', name: 'Коттедж за городом', rent: 65000, buyPrice: 22000000, slots: 6, moodBonus: 30, minLevel: 30, img: 'assets/houses/cottage.jpg' },
    { id: 'loft', name: 'Дизайнерский Лофт в центре', rent: 80000, buyPrice: 35000000, slots: 4, moodBonus: 35, minLevel: 45, img: 'assets/houses/loft.jpg' },
    { id: 'penthouse', name: 'Пентхаус в Москва-Сити', rent: 250000, buyPrice: 140000000, slots: 6, moodBonus: 50, minLevel: 65, img: 'assets/houses/penthouse.jpg' },
    { id: 'villa', name: 'Особняк на Рублёвке', rent: 600000, buyPrice: 450000000, slots: 15, moodBonus: 80, minLevel: 85, img: 'assets/houses/villa.jpg' },
    { id: 'island', name: 'Частный остров с виллой', rent: 2000000, buyPrice: 1500000000, slots: 30, moodBonus: 100, minLevel: 100, img: 'assets/houses/island.jpg' }
];

const STREET_CHAT_LOG = [
    { author: "🚨 ДПС_Инфо", text: "Внимание! На ул. Ленина рейд по 12.5.1, прячьте прямотоки!", warning: true, effect: { target: "comfort", modifier: 0.85, duration: 120 } },
    { author: "🚨 ДПС_Инфо", text: "Экипаж с люстрой стоит у ТЦ Галерея, тормозят всех тонированных.", warning: true, effect: { target: "premium", modifier: 0.90, duration: 120 } },
    { author: "🚨 ДПС_Инфо", text: "Скрытый патруль на объездной. Снимайте каркасы шторки!", warning: true },
    { author: "🚨 ДПС_Инфо", text: "Облава на парковке Ашана. Выписывают за выхлоп.", warning: true, effect: { target: "all", modifier: 0.95, duration: 90 } },
    { author: "🚨 ДПС_Инфо", text: "Камеры на МКАДе перенастроили на ремни и телефон.", warning: true },
    { author: "Vazovod_77", text: "Куплю кузов под корч ВАЗ 2107 или 2101, срочно в лс!", warning: false, effect: { target: "economy", modifier: 1.15, duration: 90 } },
    { author: "Major_Vova", text: "Завтра сходка на парковке, вход только для немцев.", warning: false },
    { author: "JDM_King", text: "Кто может заварить редуктор по-братски за пиво?", warning: false },
    { author: "Perecup_Pro", text: "Продам Солярис, не бит не крашен (крашена только крыша).", warning: false },
    { author: "Sanya_Garage", text: "Делаю капиталку за 3 дня, гарантия до ворот. Цены в лс.", warning: false },
    { author: "Mark_2_Top", text: "Ищу столб... тьфу, задний бампер на марк 2.", warning: false },
    { author: "BMW_Boy", text: "Куплю масло 10w40 бочку, желательно оптом.", warning: false },
    { author: "Podbor_Max", text: "Осматривал Камри на Лесной. Пробег кручен на 300к. Не берите!", warning: false },
    { author: "Patsan_Taz", text: "Где сейчас можно нормально угла дать, чтобы без мигалок?", warning: false },
    { author: "Auto_Lombard", text: "Выдаем займы под ПТС. Быстро, без вопросов.", warning: false },
    { author: "Maga_M5", text: "Встану на 402 метра с любым. Ставка 500к.", warning: false },
    { author: "GTI_Stage3", text: "У кого есть шнурок Вася Диагност? Надо чек скинуть перед продажей.", warning: false },
    { author: "Plenka_Center", text: "Акция! Закатай бункер в круг со скидкой 20%.", warning: false },
    { author: "Ilya_Resale", text: "Заберу ваш авто в любом состоянии за 60% от рынка. Деньги сразу.", warning: false },
    { author: "Serega_Taxi", text: "Сдам в аренду Логан под такси. 1500р/сутки.", warning: false },
    { author: "Detaling_Pro", text: "Химчистка после картошки и рассады. Вернем запах новой машины.", warning: false },
    { author: "Peredelka_Msk", text: "Переварю пороги, днище, стаканы. Недорого. Писать в личку.", warning: false },
    { author: "Secret_Buyer", text: "Ищу премиум от 300 л.с., бюджет не ограничен. Писать в ЛС.", warning: false, effect: { target: "premium", modifier: 1.2, duration: 120 } },
    { author: "Lada_Fan", text: "Пацаны, как снять стук клапанов на Приоре перед продажей? Срочно!", warning: false },
    { author: "Ivan_Perekup", text: "Скинул перекупу машину перекупа. Круговорот хлама в природе.", warning: false },
    { author: "Hustler99", text: "Кто знает, где достать номера 777 дешевле рынка?", warning: false },
    { author: "Auto_Podbor", text: "Сегодня смотрел 5 машин. Все скручены, две в тотале. Рынок мертв.", warning: false, effect: { target: "all", modifier: 0.90, duration: 60 } },
    { author: "Major_Vova", text: "Продул 500к в подпольном клубе... где тут ближайший ломбард?", warning: false },
    { author: "DriftKing", text: "Завтра ночная сходка на парковке Ашана. ДПС не звать!", warning: false },
    { author: "Crypto_Bro", text: "Словил ликвидацию на Bybit, продаю свой Гольф стейдж 2. Срочно.", warning: false },
    // Новые сообщения:
    { author: "SysAdmin", text: "Кто шарит, как AmneziaWG нормально настроить, чтобы MTU не резало на мобиле? Накипело...", warning: false },
    { author: "CNC_Master", text: "Могу вырезать любые проставки на стенс и фланцы лазером или на координатно-пробивном. Качество завод. Пишите в личку.", warning: false, effect: { target: "economy", modifier: 1.05, duration: 40 } },
    { author: "Beam_Mapper", text: "Народ, кто-то умеет JBeam файлы ковырять? Физика отваливается после переноса.", warning: false }
];

const CONTAINER_ITEMS = [
    { id: 'japan', name: 'Японский Контейнер', cost: 150000, timer: 30, badge: 'JDM & Мото', desc: 'Прямые поставки из порта Кобе.', img: 'assets/containers/japan.jpg' },
    { id: 'europe', name: 'Европейский Автовоз', cost: 450000, timer: 35, badge: 'Комфорт & Премиум', desc: 'Автомобили из Германии без пробега по РФ.', img: 'assets/containers/europe.jpg' },
    { id: 'usa_auction', name: 'Американский Аукцион', cost: 750000, timer: 40, badge: 'Битые & Маслкары', desc: 'Контейнер с Copart. Кот в мешке.', img: 'assets/containers/usa.jpg' },
    { id: 'china_ship', name: 'Китайский Сухогруз', cost: 950000, timer: 38, badge: 'Электрички & Новые', desc: 'Свежие Lixiang и Zeekr прямиком из Гуанчжоу.', img: 'assets/containers/china.jpg' },
    { id: 'dubai', name: 'Эмиратский Контейнер', cost: 1200000, timer: 45, badge: 'Катера & Суперкары', desc: 'Аукционная роскошь шейхов.', img: 'assets/containers/dubai.jpg' },
    { id: 'hangar', name: 'Заброшенный Ангар', cost: 5000000, timer: 60, badge: 'Тягачи & Гиперкары', desc: 'Списанное имущество логистического хаба!', img: 'assets/containers/hangar.jpg' }
];

const SELLER_ADS_PHRASES = [
    "«Дедушка ездил только летом на дачу!»", 
    "«Сел и поехал, мотор шепчет.»", 
    "«Перекупам и салонам не звонить!»",
    "«Прошита Stage 2, дует отлично, новый байпас.»",
    "«Машина в идеале, любые проверки за ваш счет.»",
    "«Продаю со слезами на глазах...»",
    "«Вложений не требует, только масло долить.»",
    "«Красилась только одна дверь (косметика).»",
    "«Ездила девушка, маршрут дом-работа-сад.»",
    "«Пробег родной 100%, можете проверять по базам.»",
    "«Масло не ест ни грамма, от замены до замены!»",
    "«Коробка не пинает, листает незаметно.»",
    "«В гонках не участвовала, чисто городской цикл.»",
    "«Салон пахнет новьем, никто никогда не курил.»",
    "«Третья машина в семье, стояла в теплом паркинге.»",
    "«Продаю в связи с покупкой жилья/пополнением в семье.»",
    "«Обслуживалась только у официалов, чеки на руках.»",
    "«Кузов оцинкован, ни одного рыжика!»",
    "«Юридически чистая, без штрафов и запретов.»",
    "«Двигатель контрактный, вписан в ПТС.»",
    "«По ходовке мячик, нигде ничего не стучит.»",
    "«Отдам с зимней резиной на штампах.»",
    "«Торг только у капота с деньгами в руках.»",
    "«Обмен не предлагать (разве что на квартиру в центре).»",
    "«Свои цены не предлагайте, рынок знаю.»",
    "«В салоне возили только воздух.»",
    "«Музыка на 200К, сабвуфер на полбагажника!»",
    "«Вложено много сил и средств, делал для себя.»",
    "«Комплектация максимальная, есть всё кроме люка.»",
    "«Передвигаюсь каждый день, на стоянку не поставлю.»",
    "«Состояние - музей! Капсула времени.»",
    "«От сердца отрываю, надежный как автомат Калашникова.»"
];

const EXPANDED_BUYERS_POOL = [
    { name: "Ашот, перекуп", avatar: "😎", type: "dealer", rate: 0.72, minKarma: 0, preStatus: "Жестко сбивает цену...", rejectSay: "За эти деньги я две таких возьму!" },
    { name: "Максим, подборщик", avatar: "🔍", type: "inspector", rate: 0.90, minKarma: 30, preStatus: "Лезет эндоскопом...", rejectSay: "Сделки не будет! Машина - хлам." },
    { name: "Иван Сергеевич", avatar: "👨‍🌾", type: "regular", rate: 0.85, minKarma: 20, preStatus: "Ищет повод сбить цену...", rejectSay: "Мне на дачу ездить не пойдет." },
    { name: "Артём, студент", avatar: "🧢", type: "student", rate: 0.78, minKarma: 0, preStatus: "Слушает выхлоп...", rejectSay: "Блин, стипы не хватает." },
    { name: "Елена, бухгалтер", avatar: "👩‍‍💼", type: "regular", rate: 0.95, minKarma: 50, preStatus: "Смотрит только на салон...", rejectSay: "Вы мне кажетесь подозрительным. Отказ." },
    { name: "Илья, инженер-ЧПУ", avatar: "🛠️", type: "inspector", rate: 0.82, minKarma: 20, preStatus: "Замеряет зазоры...", rejectSay: "Отклонение на 2 микрона, геометрия нарушена!" },
    { name: "Кирилл, криптотрейдер", avatar: "📱", type: "dealer", rate: 0.92, minKarma: 10, preStatus: "Смотрит графики битка...", rejectSay: "Маржин-колл, братан, денег нет." },
    { name: "Мага, суетолог", avatar: "🏎️", type: "student", rate: 0.88, minKarma: 10, preStatus: "Проверяет тонировку...", rejectSay: "Не едет она на свои деньги, брат." },
    { name: "Дядя Толя, таксист", avatar: "🚕", type: "regular", rate: 0.80, minKarma: 15, preStatus: "Считает расход топлива...", rejectSay: "Жрет много, в такси нерентабельно." },
    { name: "Саня, гонщик", avatar: "🏁", type: "student", rate: 0.85, minKarma: 0, preStatus: "Смотрит на резину...", rejectSay: "Резина лысая, угла не дать, пас." },
    { name: "Виктория, инста-дива", avatar: "💅", type: "regular", rate: 0.98, minKarma: 60, preStatus: "Делает селфи на фоне...", rejectSay: "Она не сочетается с моей сумочкой." },
    { name: "Вася, механик", avatar: "🔧", type: "inspector", rate: 0.75, minKarma: 10, preStatus: "Нюхает щуп...", rejectSay: "Масло пахнет гарью, мотор труп." },
    { name: "Дед Макар", avatar: "👴", type: "regular", rate: 0.88, minKarma: 30, preStatus: "Стучит клюкой по порогам...", rejectSay: "В мое время металл был толще. Гнилушка." },
    { name: "Тимур, мажор", avatar: "🤑", type: "dealer", rate: 0.95, minKarma: 10, preStatus: "Лениво пинает колесо...", rejectSay: "Слишком скучная, пацаны засмеют." },
    { name: "Ольга Петровна", avatar: "👵", type: "regular", rate: 0.90, minKarma: 40, preStatus: "Ищет крепления изофикс...", rejectSay: "Куда я тут внуков посажу? Тесно!" },
    { name: "Гриша, рыбак", avatar: "🎣", type: "regular", rate: 0.82, minKarma: 20, preStatus: "Проверяет объем багажника...", rejectSay: "Сюда лодка не влезет, отказ." },
    { name: "Руслан, автосалон", avatar: "🏢", type: "dealer", rate: 0.65, minKarma: 25, preStatus: "Обещает золотые горы...", rejectSay: "Ну не хотите по низу рынка — до свидания." },
    { name: "Светик, жена", avatar: "👱‍♀️", type: "regular", rate: 0.92, minKarma: 50, preStatus: "Звонит мужу посоветоваться...", rejectSay: "Муж сказал не брать эту ерунду." },
    { name: "Колян, с района", avatar: "🦧", type: "student", rate: 0.70, minKarma: 0, preStatus: "Включает магнитолу на всю...", rejectSay: "Басов не хватает, вообще не качает." },
    { name: "Альберт, коллекционер", avatar: "🧐", type: "inspector", rate: 0.98, minKarma: 80, preStatus: "Ищет оригинальные болты...", rejectSay: "С вашей репутацией я дела не веду." },
    { name: "Даша, студентка", avatar: "📚", type: "student", rate: 0.80, minKarma: 40, preStatus: "Смотрит, есть ли парктроники...", rejectSay: "Без камеры заднего вида я ее разобью." },
    { name: "Егор, перегонщик", avatar: "🛣️", type: "dealer", rate: 0.75, minKarma: 20, preStatus: "Пробивает толщиномером...", rejectSay: "Вся в шпакле, на перепродажу не пойдет." },
    { name: "Михалыч, сосед", avatar: "🍺", type: "regular", rate: 0.85, minKarma: 10, preStatus: "Дышит перегаром в салон...", rejectSay: "Не, лучше свою Волгу починю." },
    { name: "Алиса, стартапер", avatar: "💻", type: "regular", rate: 0.90, minKarma: 50, preStatus: "Ищет Bluetooth и розетки...", rejectSay: "Она недостаточно экологичная." },
    { name: "Женя, дрифтер", avatar: "🔄", type: "student", rate: 0.78, minKarma: 0, preStatus: "Проверяет заварку дифференциала...", rejectSay: "Кузов повело, боком не поедет." },
    { name: "Слепой Пью", avatar: "🦯", type: "inspector", rate: 0.99, minKarma: 50, preStatus: "Щупает машину руками...", rejectSay: "Я не вижу в ней потенциала." },
    { name: "Влад, юрист", avatar: "⚖️", type: "inspector", rate: 0.85, minKarma: 60, preStatus: "Пробивает по базам ФССП...", rejectSay: "У вас плохая история сделок, рисковать не буду." },
    { name: "Марат, строитель", avatar: "🧱", type: "regular", rate: 0.80, minKarma: 20, preStatus: "Проверяет рессоры...", rejectSay: "Тонну цемента не увезет, слабая." },
    { name: "Гоша, геймер", avatar: "🎮", type: "student", rate: 0.88, minKarma: 10, preStatus: "Ищет подсветку салона...", rejectSay: "В Форзе она выглядит круче." },
    { name: "Петр, чиновник", avatar: "💼", type: "dealer", rate: 0.95, minKarma: 70, preStatus: "Смотрит, глухая ли тонировка...", rejectSay: "Недостаточно статусная для моих задач." }
];

const DIETS = [
    { id: 'water', name: 'Вода из-под крана', cost: 0, hunger: 5, mood: -30, desc: 'Живот крутит, жить не хочется' },
    { id: 'doshik', name: 'Бич-пакет и сухари', cost: 150, hunger: 20, mood: -15, desc: 'Желудок ноет, депрессия, тяжело торговаться' },
    { id: 'home_sandwich', name: 'Бутерброд из дома', cost: 250, hunger: 30, mood: -5, desc: 'Майонез, колбаса "Красная цена", терпимо' },
    { id: 'pelmeni', name: 'Пельмени по акции', cost: 400, hunger: 45, mood: 0, desc: 'Дешево и сердито, главное сварить' },
    { id: 'energy_dog', name: 'Энергетик и сосиска', cost: 550, hunger: 35, mood: 5, desc: 'Мотор колотится, но жить можно' },
    { id: 'shaurma', name: 'Шаурма на вокзале', cost: 800, hunger: 50, mood: -5, desc: 'Сытно, но жирно и тоскливо' },
    { id: 'fastfood', name: 'Фастфуд комбо', cost: 1200, hunger: 60, mood: 10, desc: 'Бургер, картошка, кола. Классика.' },
    { id: 'stolovka', name: 'Обед в столовой', cost: 2200, hunger: 70, mood: 15, desc: 'Нормальное первое, второе и компот' },
    { id: 'pizza_delivery', name: 'Доставка пиццы', cost: 3500, hunger: 85, mood: 20, desc: 'Большая пепперони с сырным бортом' },
    { id: 'cafe', name: 'Бизнес-ланч в ресторане', cost: 6500, hunger: 90, mood: 25, desc: 'Свежий стейк, кофе и уверенность в себе' },
    { id: 'craft_burger', name: 'Крафтовый бургер с ИПА', cost: 8000, hunger: 95, mood: 35, desc: 'Хипстерский шик, настроение на высоте' },
    { id: 'elite', name: 'Шеф-повар & Мишлен', cost: 25000, hunger: 100, mood: 45, desc: 'Максимальный кураж: меньше уступок в торгах!' }
];

const BUSINESS_DATA = [
    { id: 'wash', name: 'Автомойка 24/7', minLevel: 5, income: 900, level: 0, cost: 90000, stored: 0, perk: 'Скидка 50% на полировку и химчистку' },
    { id: 'shina', name: 'Шиномонтаж «У Алика»', minLevel: 8, income: 1500, level: 0, cost: 150000, stored: 0, perk: '+10% к стоимости авто на правильных дисках' },
    { id: 'sto', name: 'СТО дяди Вани', minLevel: 12, income: 2200, level: 0, cost: 300000, stored: 0, perk: 'Скидка 40% на ремонт мотора' },
    { id: 'shaurma', name: 'Точка Шаурмы у трассы', minLevel: 15, income: 3000, level: 0, cost: 450000, stored: 0, perk: 'Бесплатное питание раз в день (ХП на макс)' },
    { id: 'detailing', name: 'Детейлинг Студия', minLevel: 20, income: 6500, level: 0, cost: 950000, stored: 0, perk: '+35% к баллам на Автошоу' },
    { id: 'razborka', name: 'Авторазборка «Последний путь»', minLevel: 22, income: 8000, level: 0, cost: 1200000, stored: 0, perk: 'Детали на ремонт обходятся дешевле на 30%' },
    { id: 'evacuator', name: 'Служба Эвакуации 24/7', minLevel: 25, income: 9500, level: 0, cost: 1500000, stored: 0, perk: 'Шанс 50% бесплатно спасти авто со штрафстоянки' },
    { id: 'katalizator', name: 'Скупка катализаторов', minLevel: 28, income: 12000, level: 0, cost: 1900000, stored: 0, perk: 'Дополнительный доход при вырезке ката (P0420)' },
    { id: 'perekup_office', name: 'Офис перекупов «Рога и Авто»', minLevel: 30, income: 15000, level: 0, cost: 2500000, stored: 0, perk: '+15% шанс впарить хлам лоху' },
    { id: 'taxi', name: 'Таксопарк (15 авто)', minLevel: 32, income: 18000, level: 0, cost: 3800000, stored: 0, perk: 'Пассивный доход и +1 🤝 связь каждый день' },
    { id: 'rental', name: 'Прокат авто «Драйв»', minLevel: 35, income: 21000, level: 0, cost: 4500000, stored: 0, perk: 'Машины в аренде не требуют налога' },
    { id: 'tonirovka', name: 'Студия Тонировки «Бункер»', minLevel: 38, income: 24000, level: 0, cost: 5200000, stored: 0, perk: 'Менты реже останавливают за 12.5.1' },
    { id: 'zvuk', name: 'Студия Автозвука', minLevel: 40, income: 27000, level: 0, cost: 6000000, stored: 0, perk: '+20% настроения от поездок на своем авто' },
    { id: 'chip_tuning', name: 'Чип-Тюнинг «Stage 100»', minLevel: 42, income: 30000, level: 0, cost: 7500000, stored: 0, perk: 'Бесплатный Stage 1 для своих тачек' },
    { id: 'lombard', name: 'Автоломбард', minLevel: 45, income: 35000, level: 0, cost: 9500000, stored: 0, perk: 'Шанс выкупить тачку за 50% от рынка' },
    { id: 'parking_bityo', name: 'Стоянка тотальных авто', minLevel: 48, income: 40000, level: 0, cost: 12000000, stored: 0, perk: 'Можно хранить неограниченно битых тачек' },
    { id: 'dealer', name: 'Автосалон Premium', minLevel: 50, income: 45000, level: 0, cost: 15000000, stored: 0, perk: '+15% к шансу быстрой продажи авто на площадке' },
    { id: 'customs', name: 'Таможенный брокер', minLevel: 55, income: 60000, level: 0, cost: 22000000, stored: 0, perk: 'Скидка 20% на растаможку контейнеров' },
    { id: 'azs', name: 'Сеть АЗС «Бодяга-Ойл»', minLevel: 60, income: 80000, level: 0, cost: 35000000, stored: 0, perk: 'Бензин для ваших машин бесплатен' },
    { id: 'elite_parking', name: 'Подземный VIP-Паркинг', minLevel: 65, income: 120000, level: 0, cost: 55000000, stored: 0, perk: '+10 мест в гараже, 0% угона' },
    { id: 'insurance', name: 'Страховая «Надежный кидок»', minLevel: 70, income: 200000, level: 0, cost: 100000000, stored: 0, perk: 'Полный возврат при тотале вашей машины' }
];

const OBD_ERRORS = [
    { text: "P0101: Выход сигнала ДМРВ из допустимого диапазона", cost: 5000, severity: "Низкая" },
    { text: "P0113: Высокий уровень сигнала датчика температуры впуска", cost: 2500, severity: "Низкая" },
    { text: "P0133: Медленный отклик кислородного датчика (Лямбда)", cost: 8000, severity: "Средняя" },
    { text: "P0171: Слишком бедная смесь (Подсос воздуха)", cost: 4000, severity: "Средняя" },
    { text: "P0172: Слишком богатая смесь (Льют форсунки)", cost: 12000, severity: "Средняя" },
    { text: "P0234: Передув турбины (Неисправен клапан N75)", cost: 16000, severity: "Высокая" },
    { text: "P0299: Недодув турбины (Утечка или хана улитке)", cost: 45000, severity: "Критическая" },
    { text: "P0300: Множественные пропуски зажигания", cost: 11000, severity: "Средняя" },
    { text: "P0301: Пропуски зажигания в 1 цилиндре (Свеча/Катушка)", cost: 3500, severity: "Низкая" },
    { text: "P0325: Неисправность цепи датчика детонации", cost: 4500, severity: "Низкая" },
    { text: "P0335: Ошибка датчика положения коленвала (Глохнет)", cost: 6000, severity: "Высокая" },
    { text: "P0340: Ошибка датчика распредвала", cost: 5500, severity: "Высокая" },
    { text: "P0401: Слишком низкий расход в системе EGR", cost: 15000, severity: "Средняя" },
    { text: "P0420: Эффективность катализатора ниже порога", cost: 25000, severity: "Средняя" },
    { text: "P0442: Небольшая утечка в системе EVAP", cost: 1500, severity: "Низкая" },
    { text: "P0500: Нет сигнала от датчика скорости", cost: 3000, severity: "Низкая" },
    { text: "P0700: Неисправность системы управления АКПП", cost: 8000, severity: "Высокая" },
    { text: "P0720: Ошибка датчика частоты вращения вала АКПП", cost: 12000, severity: "Высокая" },
    { text: "P0730: Некорректное передаточное отношение (Букс АКПП)", cost: 85000, severity: "Критическая" },
    { text: "P0741: Блокировка гидротрансформатора не работает", cost: 40000, severity: "Критическая" },
    { text: "P2711: Недостоверные данные о передаче (Мехатроник DSG)", cost: 65000, severity: "Критическая" },
    { text: "P0011: Положение распредвала - избыточное опережение (Vanos)", cost: 35000, severity: "Критическая" },
    { text: "P0016: Рассинхронизация распредвала и коленвала", cost: 85000, severity: "Критическая (Цепь ГРМ)" },
    { text: "U0100: Потеря связи с ЭБУ двигателя (Проводка)", cost: 20000, severity: "Высокая" },
    { text: "C1201: Сбой системы курсовой устойчивости (ABS/ESP)", cost: 18000, severity: "Высокая" },
    { text: "B1000: Внутренняя ошибка блока SRS (Стреляные подушки)", cost: 30000, severity: "Критическая" },
    { text: "P1296: Ошибка системы охлаждения (Термостат)", cost: 8000, severity: "Средняя" },
    { text: "P2261: Механическая неисправность байпасного клапана", cost: 9000, severity: "Средняя" },
    { text: "P2101: Неисправность привода дроссельной заслонки", cost: 14000, severity: "Высокая" },
    { text: "P0087: Слишком низкое давление в топливной рампе (ТНВД)", cost: 55000, severity: "Критическая" }
];

const DAILY_REWARDS_CONFIG = [
    { day: 1, title: "+20k ₽ & 10 ⛽", reward: { cash: 20000, fuel: 10 } },
    { day: 2, title: "+40k ₽ & 1 🤝", reward: { cash: 40000, connections: 1 } },
    { day: 3, title: "+75k ₽ & 10 ⭐", reward: { cash: 75000, stars: 10 } },
    { day: 4, title: "+120k ₽ & 1 🤝", reward: { cash: 120000, connections: 1 } },
    { day: 5, title: "+200k ₽ & 15 ⭐", reward: { cash: 200000, stars: 15 } },
    { day: 6, title: "+350k ₽ & Бак", reward: { cash: 350000, fuel: 100 } },
    { day: 7, title: "+600k ₽ & 25 ⭐", reward: { cash: 600000, stars: 25, specialPlate: "Х777ХХ 77" } }
];

// --- БАЗА ДЛЯ ГАРАЖНЫХ НАХОДОК ---
const BARN_FINDS = [
    { name: "ВАЗ-2101 «Копейка» (Дрифт-Спек)", power: 160, type: 'economy', basePrice: 850000, marketValue: 1250000, img: "assets/cars/barn/vaz2101_drift.jpg" },
    { name: "BMW E30 Coupe", power: 170, type: 'comfort', basePrice: 650000, marketValue: 1300000, img: "assets/cars/barn/e30.jpg" },
    { name: "Nissan Silvia S13", power: 200, type: 'comfort', basePrice: 900000, marketValue: 1800000, img: "assets/cars/barn/silvia.jpg" },
    { name: "VW Golf VI GTI (Stage 2 Project)", power: 280, type: 'comfort', basePrice: 1100000, marketValue: 1900000, img: "assets/cars/barn/golf6.jpg" },
    { name: "ГАЗ-24 «Волга» V8", power: 220, type: 'economy', basePrice: 700000, marketValue: 1500000, img: "assets/cars/barn/volga24.jpg" }
];